# Generated by Django 2.2 on 2019-05-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('goods_sort', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('keys', models.IntegerField()),
            ],
            options={
                'db_table': 'goods_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('create_time', models.CharField(max_length=50)),
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'search_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('goods_info', models.CharField(blank=True, max_length=50, null=True)),
                ('store_name', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_rating', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('source_site', models.CharField(blank=True, max_length=50, null=True)),
                ('image_file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'store_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
